site_name: Moonstone Theme for MkDocs
site_url: https://www.majordojo.com
site_description: A project documentation theme for MkDocs.
site_author: Byrne Reese

repo_url: https://github.com/byrnereese/mkdocs-moonstone/
edit_uri: ""

plugins:
#  - git-committers:
#      repository: 
#      branch: 
#      token: 
  - search
  - bootstrap-tables

theme:
    name: moonstone

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - codehilite:
      linenums: "None"

nav:
  - Home: index.md
  - User Guide:
    - Installation: guide/install.md
    - Options: guide/options.md
  - Style Guide:
    - Text Styles: styles/text.md
    - Tables: styles/tables.md
    - Syntax Highlighting: styles/code.md
    - Admonitions: styles/admonitions.md
  - About:
    - License: license.md

extra_css:
    - css/extra.css

copyright: Copyright &copy; 2019 <a href="https://majordojo.com/">Byrne Reese</a>
google_analytics: 

