site_name: Moonstone Theme for MkDocs
site_url: https://www.majordojo.com
site_description: A project documentation theme for MkDocs.
site_author: Byrne Reese

repo_url: https://github.com/byrnereese/mkdocs-moonstone/
edit_uri: ""

plugins:
  - git-committers:
      repository: byrnereese/mkdocs-moonstone
      branch: master
      token:
        !!python/object/apply:os.getenv ["MOONSTONE_GIT_COMMITTERS_APIKEY"]
  - search
  - bootstrap-tables

theme:
  name: moonstone
  custom_dir: 'custom_theme/'
  fluid_layout: False

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - codehilite:
      linenums: "None"

nav:
  - Home: index.md
  - User Guide:
    - Installation: guide/install.md
    - Theme Customization: guide/options.md
    - Page-level Customization: guide/page-options.md
  - Style Guide:
    - Text Styles: styles/text.md
    - Tables: styles/tables.md
    - Syntax Highlighting: styles/code.md
    - Admonitions: styles/admonitions.md
  - Support:
    - Bug Reports & Feature Requests: support.md
  - About:
    - License: license.md

extra_css:
    - css/extra.css

copyright: Copyright &copy; 2019 <a href="https://majordojo.com/">Byrne Reese</a>
google_analytics: 

